### ISSUE TITLE
Fix URL not opening while running the program.

### ISSUE THREAD

**Issue by amulyagaur** [amulyagaur/EasyMP3#3]

**Comment by satyabansahoo2000** [comment]
@amulyagaur u have the URL as **downloadming2** which is not available, you can just change it **downloadming3**

**Comment by amulyagaur** [comment]
> @amulyagaur u have the URL as **downloadming2** which is not available, you can just change it **downloadming3**

Correct.. Fixed in a PR. 
Thanks
