### ISSUE TITLE
Refactor code to split it into different methods having single responsiility

### ISSUE THREAD

**Issue by amulyagaur** [amulyagaur/EasyMP3#9]
Currently whole code is in just one function which is not very readable and easy to understand.

**Comment by sculley** [comment]
Hello, Could I be assigned to this issue please?

**Comment by amulyagaur** [comment]
Sure Sam👍

**Comment by Deshdeepak1** [comment]
I would like to work on this.

**Comment by amulyagaur** [comment]
Closing this. Thank u all for contributing
